# Generated by Django 2.2 on 2021-12-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=10)),
                ('Entity_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_key', models.CharField(max_length=100)),
                ('acct_open_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='customer_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transfer_key', models.CharField(max_length=100)),
                ('Transaction_Amount', models.IntegerField()),
                ('Transcation_Origin', models.CharField(max_length=10)),
                ('Transaction_date', models.DateTimeField()),
                ('account_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.customer_account_info')),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(max_length=100)),
                ('party_open_date', models.DateField()),
                ('residential_country_cd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.countries_info')),
            ],
        ),
        migrations.AddField(
            model_name='customer_account_info',
            name='primary_party_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.customer_info'),
        ),
    ]
